framework:
    default_locale: '%default_locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%default_locale%'

        # required for loco
        enabled_locales: ['%default_locale%']
        providers:
            loco:
                dsn: '%env(LOCO_DSN)%'
                domains: ['messages']
                locales: ['%default_locale%']
